### ISSUE TITLE
Gravity bridge to BSC

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtecharchive/threefold_hub#13]

**Comment by OmarElawady** [comment]
Trying the standard flow for a bridge between Ethereum testnet and threefold_hub and then will do it on Binance. It should be roughly the following steps:
- including the gravity module in threefold_hubd and starting the chain
- starting the Ethereum node (don't know why yet)
- delegating an Ethereum account to do the signing on behalf of the validator
- deploying [`Gravity.sol`](https://github.com/Gravity-Bridge/Gravity-Bridge/blob/main/solidity/contracts/Gravity.sol) with the validator delegated address on Ethereum testnet.
- starting the [orchestrator](https://github.com/Gravity-Bridge/Gravity-Bridge/releases/tag/v1.4.3-beta) (gbt) with the contract address and the relevant endpoints

**Comment by OmarElawady** [comment]
starting a chain like the "gravity bridge" chain to allow bridging tokens from/to BSC. The [gravity](https://github.com/Gravity-Bridge/Gravity-Bridge/releases/tag/v1.4.1) binary is used for now but it will be replaced by the threefold_hub binary with the gravity module added to it. There were some issues with latest version but 1.4.1 worked fine:
1. Add an account to the keyring. The mnemonic is fixed here for repeatability.
```bash 
gravity add key omar --recover # enter "reunion castle royal proud suggest stable bus unlock away upon enrich snake script hand flag black member private garlic program carbon cross brush best" as seed phrase
```
2. initialize genesis:
```bash 
gravity init omar --chain-id threefold-hub # not sure what moniker means yet
```
3. Add an account to genisis with the some tokens
```bash
gravity add-genesis-account omar 200000000stake,20000gravity
```
4. Create a validator with 10..stake staked and delegate its signing power to the eth address specified. The account with the eth address can then sign transactions sent to ethereum. The ethereum address should be replaced with the account you want to delegate to (you must have its private key).
```bash
# eth account address the validator delegates to, cosoms address of the validator (omar)
gravity gentx --moniker omar omar 100000000stake 0xD6DBC796aC81DC34bDe3864f1F2c8f40742D85Dc gravity1rd39mdjf5xe87prc3klwwfxxuxetcyjntegnkv --chain-id=threefold-hub # 
```
5. The previous command creates a gentx json file. This command adds it to the genesis file.
```bash
gravity collect-gentxs # moves the previous gentx to genisis.json
```
6. Start a BSC [light](https://github.com/threefoldtech/threefold_hub/tree/development/research/bridges/BSC) node. Took ~3 hours to sync.
7. Deploy the Gravity.sol contract. We used remix. The [Gravity.sol](https://github.com/Gravity-Bridge/Gravity-Bridge/blob/v1.4.1/solidity/contracts/Gravity.sol) file and [CosmosToken](https://github.com/Gravity-Bridge/Gravity-Bridge/blob/v1.4.1/solidity/contracts/CosmosToken.sol) was needed to be copied into contracts, compiled, and then deployed into BSC. The contract address should then be saved for later use. For deployment, the validator set used is `["0xD6DBC796aC81DC34bDe3864f1F2c8f40742D85Dc"]`, the powers (should add up to 2^32) is `[4294967296]`, and the id is any random 32 letter nonce.
 
8. Start the [orchestrator](https://github.com/Gravity-Bridge/Gravity-Bridge/releases/tag/v1.5.0) binary (gbt).
```bash
./gbt -v orchestrator --cosmos-phrase "reunion castle royal proud suggest stable bus unlock away upon enrich snake script hand flag black member private garlic program carbon cross brush best" -e "<ethereum-private-key>" --gravity-contract-address "<the gravity contract address>" -f 1gravity --ethereum-rpc "http://localhost:8575"
```
9. Tokens can now be transfered from BSC to cosmos. Wasn't able to find the contract address of BNB (maybe because it's the native token of the chain), so used the [ETH](https://testnet.bscscan.com/token/0xd66c6b4f0be8ce5b39d52e0fd1344c389929b378?a=0xD6DBC796aC81DC34bDe3864f1F2c8f40742D85Dc)  instead. You can get some from the binance testnet [faucet](https://testnet.binance.org/faucet-smart). The token contract address from the previous link is used as a token identifier on the chain and in the following command. 
```bash
./gbt client eth-to-cosmos --ethereum-key '<source-account-private-key>' --gravity-contract-address '<gravity-contract-address>' --token-contract-address '0xd66c6B4F0be8CE5b39D52E0Fd1344c389929B378' --amount .000001 --destination gravity1rd39mdjf5xe87prc3klwwfxxuxetcyjntegnkv --ethereum-rpc http://localhost:8575
```
10. The orchestrator should pick up the request in a short time and then the transfer the tokens to the destination address. The balances can be viewed by `gravity query bank balances gravity1rd39mdjf5xe87prc3klwwfxxuxetcyjntegnkv`

TODO:
1. For some reason, the relayer in the orchestrator doesn't submit the transaction batch generated when transfering the money back to the ethereum account. From the docs, seems like the relayer makes a decision to submit the batch based on the profit it'll get from it. The gas is paid in BNBs while the bridge fees is in ETHs in our case, so how does it find its profitability from performing this transaction. The transactions are signed on cosmos side and the signature is viewable and it can be submitted manually through the gravity contract.
2. Transferring cosmos-originating tokens to BSC and back to cosmos.

**Comment by OmarElawady** [comment]
Regarding the relaying issue. The relayer is configurable to do Batch building and Batch relaying based on the profitability it will get, or to always do the relaying. It consults uniswap to check the difference between the gas currency (WETH) and the currency of the fee paid to it. After configuring it to always do the batching and relaying, it worked correctly. It should be checked if the relayer will require changes to perform this calculation with TFT on binance (if it's not on uniswap).

TODO:
The token appears on the cosmos chain as `gravity<token-contract-on-binance>`. Checking if there's a way to make the token appear as a native token (e.g. "TFT"). The genesis contains a parameter `erc20_to_denom` which looks promising but with no docs.

**Comment by OmarElawady** [comment]
After checking the gravity bridge [handling](https://github.com/Gravity-Bridge/Gravity-Bridge/blob/v1.4.2/module/x/gravity/keeper/attestation_handler.go#L98) of sending tokens from binance to cosmos. It considers tokens in `erc20_to_denom` in genesis or any token added after as "cosmos-originated". When it receives a request to send the money to cosmos, if the token is cosmos-originated, it doesn't mint new tokens, resulting in an error as the bridge account initially doesn't contain any tokens. So, there are three ways to approach this:
- work with `gravity<token-contract-address>`
- fork the gravity module and add extra handling for tokens to appear as native 
- fund the bridge account at genesis with enough tokens so that it won't need new ones. Sending from Binance to cosmos would unlock the transferred amount from the gravity bridge, and it should always succeed if the gravity bridge was initialized with correct amount (> max TFTs). And sending from cosmos to Binance should work if the bridge contract on Binance has enough money. If it fails, the batch times out and the money should be refunded. A downside of this approach is that `threefold_hubd query bank total` gives a misleading number for the amount of TFTs on the chain.

And regarding the relayer deciding the profitability of a batch, it currently works with uniswap smart contract. To make it work with with Binance:
- we can relay all batches, but will cost a lot of fees
- fork the relayer binary and make it work with [pancakeswap](https://api.pancakeswap.info/api/v2/tokens/0x8f0FB159380176D324542b3a7933F0C2Fd0c2bbf) api
- for the relayer and force a certain fee (like done in the portal now).

**Comment by OmarElawady** [comment]
Some numbers:
```
1 BNB <=> 425 BUSD
1 BUSD <=> 13 TFT

average gas price on bsc mainnet (for ~6 months): 7 gwei = 7e-9 BNB = 4e-5 TFT
gas price has relatively low variance. it lies between 6 and 8

batch submit gas base: 60000
gas increase per transaction (including the first one): 10000
so making 10 transactions would cost 60000 + 10000 * 10 = 160000

batch base price: 2.3TFT
batch price increase per transaction: .4TFT
```
Currently, the relayer code assumes a fixed 200000 gas for a batch, but it can be modified to use the approximations above.

And this is what the fork solutions would [look like](https://github.com/OmarElawady/Gravity-Bridge/pull/1/files)
