### ISSUE TITLE
Do we need the crisis module?

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtecharchive/threefold_hub#60]
I don't think there are any invariants registered, so it has no value at the moment

**Comment by OmarElawady** [comment]
We don't have invariants registered. But there are some registered by the band, distribution, staking, and gov modules. I believe that when the invariant is broken, it's a bug in the the module. It can be caused by a bad upgrade for example. The crisis module halts the chain so that not a lot is built up upon a bad state of the chain. And then it can be hard-forked or upgrade-skipped with proper fixes.

An example of a check for an invariant is: `threefold_hubd tx crisis invariant-broken bank total-supply --chain-id threefold-hub-testnet --node https://threefoldhub.test.gridtesting.xyz:26657 --gas-prices 80TFT --from placeholder --keyring-backend test --broadcast-mode block --gas-adjustment 1.3 --gas auto --home ~/.threefold_hub_devnet`

Should it be removed or not?

**Comment by robvanmieghem** [comment]
thanks, just leave it in then. Can you add your findings to docs/crisis.md ?

**Comment by robvanmieghem** [comment]
Re-opened because of my question to add the findings to docs/crisis.md .

**Comment by OmarElawady** [comment]
Updated https://github.com/threefoldtech/threefold_hub/blob/development/docs/crisis.md
